# Generated by Django 5.1.3 on 2024-12-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trainingsession_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='exercise_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['exercise_name'], name='api_youtube_exercis_fa30fc_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['video_id'], name='api_youtube_video_i_e7ad41_idx'),
        ),
    ]
