# Generated by Django 5.1.1 on 2024-09-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="workout_days",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
