# Generated by Django 5.1.3 on 2024-12-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_youtubevideo_exercise_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
