# Generated by Django 5.1.1 on 2024-09-27 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_workout_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
