# Generated by Django 5.1.1 on 2024-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_workoutplan_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="plan_data",
            field=models.TextField(),
        ),
    ]
