# Generated by Django 5.1.1 on 2024-09-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_workoutplan_plan_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.JSONField(),
        ),
    ]
