# Generated by Django 5.1.3 on 2024-12-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trainingsession_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsessionexercise',
            options={'verbose_name': 'Training Session Exercise', 'verbose_name_plural': 'Training Session Exercises'},
        ),
        migrations.AlterUniqueTogether(
            name='trainingsessionexercise',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainingsession'),
        ),
    ]
