# Generated by Django 5.1.1 on 2024-09-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_exercise_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="plan_data",
            field=models.JSONField(),
        ),
    ]
