# Generated by Django 5.1.3 on 2024-12-15 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_trainingsessionexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='average_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='emoji_feedback',
            field=models.CharField(blank=True, choices=[('😀', 'Great'), ('🙂', 'Good'), ('😐', 'Okay'), ('😕', 'Not Good'), ('😞', 'Bad')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='feedback_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='heart_rate_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='heart_rate_pre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='intensity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='api.workoutplan'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='workout_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='max_heart_rate',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='time',
        ),
    ]
