# Generated by Django 5.1.3 on 2024-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_trainingsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(default=dict, help_text='Structured instructions including setup, execution steps, and form tips'),
        ),
    ]
