# Generated by Django 5.1.1 on 2024-09-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_workoutplan_plan_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="plan_data",
            field=models.TextField(),
        ),
    ]
