# Generated by Django 5.1.1 on 2024-09-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_user_additional_goals_alter_user_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
