# Generated by Django 5.1.3 on 2024-12-18 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_exercise_muscle_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='exercises',
            field=models.ManyToManyField(related_name='training_sessions', through='api.TrainingSessionExercise', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions_through', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_through', to='api.trainingsession'),
        ),
    ]
