# Generated by Django 5.1.3 on 2024-12-18 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_trainingsession_exercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='api.trainingsession'),
        ),
    ]
