# Generated by Django 5.1.3 on 2024-12-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_trainingsession_unique_user_date_workout'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'date', 'workout_plan'], name='api_trainin_user_id_878e99_idx'),
        ),
    ]
