# Generated by Django 5.1.3 on 2024-12-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_trainingsession_api_trainin_user_id_878e99_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['videoId'], name='api_exercis_videoId_8cd66f_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='api_exercis_name_5f20ca_idx'),
        ),
    ]
