# Generated by Django 5.1.3 on 2024-12-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_exercise_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('flexibility', 'Flexibility'), ('balance', 'Balance'), ('endurance', 'Endurance'), ('power', 'Power'), ('speed', 'Speed'), ('agility', 'Agility'), ('plyometric', 'Plyometric'), ('core', 'Core'), ('cardio', 'Cardio'), ('yoga', 'Yoga'), ('stretching', 'Stretching'), ('recovery', 'Recovery')], default='strength', max_length=20),
        ),
    ]
