# Generated by Django 5.1.1 on 2024-10-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                    ("Prefer not to say", "Prefer not to say"),
                ],
                default="Prefer not to say",
                max_length=20,
            ),
        ),
    ]
