# Generated by Django 5.1.1 on 2024-10-04 01:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_trainingsession_sessionfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="workout_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.workoutplan"
            ),
        ),
    ]
