# Generated by Django 5.1.1 on 2024-10-04 02:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_trainingsession_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionfeedback",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="sessionfeedback",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sessionfeedback",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="sessionfeedback",
            name="session",
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="emoji_feedback",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="session_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="training_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.trainingsession",
            ),
        ),
        migrations.AddField(
            model_name="sessionfeedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
