# Generated by Django 5.1.1 on 2024-10-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_equipment_strengthgoal_alter_user_workout_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
