# Generated by Django 5.1.1 on 2024-10-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_equipment_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="strength_goals",
        ),
        migrations.AddField(
            model_name="user",
            name="strength_goals",
            field=models.ManyToManyField(blank=True, to="api.strengthgoal"),
        ),
    ]
