# Generated by Django 5.1.1 on 2024-10-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_remove_user_strength_goals_user_strength_goals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="equipment",
        ),
        migrations.AddField(
            model_name="user",
            name="equipment",
            field=models.ManyToManyField(blank=True, to="api.equipment"),
        ),
    ]
