# Generated by Django 5.1.1 on 2024-10-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_remove_user_equipment_user_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="emoji_feedback",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="session_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
