# Generated by Django 5.1.1 on 2024-10-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_trainingsession_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionfeedback",
            name="training_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="api.trainingsession",
            ),
        ),
    ]
