# Generated by Django 5.1.1 on 2024-10-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_alter_sessionfeedback_training_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="emoji_feedback",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "😞 Terrible"),
                    (1, "😟 Very Bad"),
                    (2, "😐 Bad"),
                    (3, "🙂 Okay"),
                    (4, "😃 Good"),
                    (5, "😄 Awesome"),
                ],
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="SessionFeedback",
        ),
    ]
