# Generated by Django 5.1.1 on 2024-10-09 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_trainingsession_emoji_feedback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("difficulty_rating", models.PositiveSmallIntegerField()),
                (
                    "emoji_reaction",
                    models.CharField(
                        choices=[
                            ("😊", "Happy"),
                            ("😐", "Neutral"),
                            ("😞", "Sad"),
                            ("👍", "Thumbs Up"),
                            ("👎", "Thumbs Down"),
                        ],
                        default="😊",
                        max_length=2,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "week_number")},
            },
        ),
    ]
