# Generated by Django 5.1.1 on 2024-10-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_weeklyfeedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeeklyFeedback",
        ),
    ]
