# Generated by Django 5.1.1 on 2024-10-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_delete_weeklyfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="week_number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
