# Generated by Django 5.1.2 on 2024-10-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_workoutplan_week_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="week_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="week_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
