# Generated by Django 5.1.2 on 2024-10-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_trainingsession_week_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="trainingsession",
            unique_together={("user", "date", "session_name")},
        ),
    ]
