# Generated by Django 5.1.2 on 2024-10-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_user_membership_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="youtube_video_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
