# Generated by Django 5.1.1 on 2024-10-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_exercise_youtube_video_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="youtube_video_id",
            new_name="videoId",
        ),
    ]
