# Generated by Django 5.1.2 on 2024-10-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_rename_youtube_video_id_exercise_videoid"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="dashboard_background",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="workoutplan_background",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
