# Generated by Django 5.1.2 on 2024-10-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_workoutplan_dashboard_background_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
