# Generated by Django 5.1.2 on 2024-10-23 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
