# Generated by Django 5.1.2 on 2024-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_workoutplan_dashboard_background_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="dashboard_background",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="workoutplan_background",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
