# Generated by Django 5.1.2 on 2024-10-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alter_workoutplan_dashboard_background_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("thumbnail_url", models.URLField()),
                ("video_url", models.URLField()),
                ("cached_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
