# Generated by Django 5.1.2 on 2024-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_youtubevideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="exercise_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="youtubevideo",
            name="video_id",
            field=models.CharField(max_length=20),
        ),
    ]
