# Generated by Django 5.1.2 on 2024-10-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_youtubevideo_exercise_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubevideo",
            name="exercise_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
