# Generated by Django 5.1.2 on 2024-11-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_alter_trainingsession_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsessionexercise",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
