# Generated by Django 5.1.3 on 2024-11-30 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_unique_constraint_workoutplan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
