# Generated by Django 5.1.3 on 2024-11-30 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_workoutplan_dashboard_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='intensity_level',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='average_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='exercises',
            field=models.ManyToManyField(through='api.TrainingSessionExercise', to='api.exercise'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='intensity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='max_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='workout_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance'), ('Endurance', 'Endurance'), ('Power', 'Power'), ('Speed', 'Speed'), ('Agility', 'Agility'), ('Plyometric', 'Plyometric'), ('Core', 'Core')], default='Strength', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_session_exercises', to='api.trainingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingsessionexercise',
            unique_together={('training_session', 'exercise')},
        ),
    ]
