# Generated by Django 5.1.3 on 2024-11-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_trainingsession_intensity_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together={('user', 'date', 'workout_type')},
        ),
    ]
