# Generated by Django 5.1.3 on 2024-11-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_trainingsession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('flexibility', 'Flexibility'), ('balance', 'Balance'), ('endurance', 'Endurance'), ('power', 'Power'), ('speed', 'Speed'), ('agility', 'Agility'), ('plyometric', 'Plyometric'), ('core', 'Core'), ('cardio', 'Cardio')], default='strength', max_length=20),
        ),
    ]
