# Generated by Django 5.1.3 on 2024-11-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_exercise_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsessionexercise',
            name='average_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsessionexercise',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsessionexercise',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsessionexercise',
            name='intensity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingsessionexercise',
            name='max_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
