# Generated by Django 5.1.3 on 2024-12-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_workoutplan_dashboard_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsessionexercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
