# Generated by Django 5.1.3 on 2024-12-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_exercise_videos'),
        ('api', '0061_alter_trainingsessionexercise_intensity_and_more'),
    ]

    operations = [
    ]
