# Generated by Django 5.1.3 on 2024-12-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_merge_20241209_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='workout_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Light Cardio', 'Light Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance'), ('Endurance', 'Endurance'), ('Power', 'Power'), ('Speed', 'Speed'), ('Agility', 'Agility'), ('Plyometric', 'Plyometric'), ('Core', 'Core')], max_length=20),
        ),
    ]
