# Generated by Django 5.1.3 on 2024-12-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_trainingsession_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='source',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
