# Generated by Django 5.1.3 on 2024-12-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_trainingsession_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='source',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('manual', 'Manual')], default='completed', max_length=20),
        ),
    ]
