# Generated by Django 5.1.1 on 2024-09-30 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_user_email"),
        ("api", "0016_handle_empty_emails"),
    ]

    operations = []
