# Generated by Django 5.1.1 on 2024-09-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_handle_empty_emails"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("email",),
                name="unique_email_when_not_null",
            ),
        ),
    ]
