# Generated by Django 5.1.1 on 2024-09-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_user_options_user_unique_email_when_not_null"),
        ("api", "0020_handle_empty_emails"),
    ]

    operations = []
